<a href="https://colab.research.google.com/github/RishikaBhawsingka/NLP-ML-project/blob/main/03_Feature_Engineering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Goal:Convert text into numbers, because ML models cannot understand text.
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
from datasets import load_dataset

dataset = load_dataset("google-research-datasets/go_emotions")
import pandas as pd
from datasets import load_dataset

dataset = load_dataset("google-research-datasets/go_emotions")

train_df = pd.DataFrame(dataset["train"])
validation_df = pd.DataFrame(dataset["validation"])
test_df = pd.DataFrame(dataset["test"])

train_df.to_csv("train.csv", index=False)
validation_df.to_csv("validation.csv", index=False)
test_df.to_csv("test.csv", index=False)

train = pd.read_csv("/content/train.csv")
validation = pd.read_csv("/content/validation.csv")
test = pd.read_csv("/content/test.csv")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md:   0%|          | 0.00/9.40k [00:00<?, ?B/s]

simplified/train-00000-of-00001.parquet: reconstructing file:   0%|          |  0.00B / 2.77MB

simplified/train-00000-of-00001.parquet: downloading bytes:           |  0.00B

simplified/validation-00000-of-00001.par(…): reconstructing file:   0%|          |  0.00B /  350kB

simplified/validation-00000-of-00001.par(…): downloading bytes:           |  0.00B

simplified/test-00000-of-00001.parquet: reconstructing file:   0%|          |  0.00B /  347kB

simplified/test-00000-of-00001.parquet: downloading bytes:           |  0.00B

Generating train split:   0%|          | 0/43410 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/5426 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/5427 [00:00<?, ? examples/s]

In [ ]:
import os

print(os.listdir('/content'))

['.config', 'train.csv', 'validation.csv', 'test.csv', 'sample_data']

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import os

print(os.listdir('/content/drive/MyDrive'))

['RISHIKA 9 A answer sheet.pdf', '20201025_083522.mp4', 'Selina Concise Chemistry Class 9 ICSE Solutions Study of Gas Laws - A Plus Topper', 'letter homework. .pdf', 'Aarushi(00918584916824)_20220907181726.mp3', 'IMG_20240823_130427_198.jpg', 'Antiragging Affidavit', 'Document from Rishika dob.pdf', 'Classroom', 'Rishika_Bhawsingka_GSSoC_Resume.docx', 'Colab Notebooks', 'Untitled document.gdoc', 'resume.gdoc', 'Google Earth', 'Screenshot_2025-12-20-12-14-48-477_com.instagram.android.jpg', 'IMG_20251220_120925.jpg', 'Screenshot_2025-12-20-12-29-03-926_com.linkedin.android.jpg', 'IMG_20251220_123313.jpg', 'Screenshot_2025-12-20-12-35-33-834_com.android.chrome.jpg', 'Payment proof.pdf', 'Copy of DSA patterns Cheat Sheet.gsheet', 'The Employability Equation - Insyte-i.pdf', 'Certificate video-1.pdf', 'Saved from Chrome', 'Peach and White Psychology Slide Presentation  (1).pptx', 'Odoo Hackathon Participant Document.gdoc', 'tell me how can i implement all this ? i will nee....gdoc', 'Research work personal', 'Project Final Year.gsheet', 'SRS', 'SRS_ss', 'Copy of bct.pdf', 'BCT AWS project', 'HumanBehaviourSimulator']

In [ ]:
import os

os.makedirs('/content/drive/MyDrive/HumanBehaviourSimulator', exist_ok=True)

In [ ]:
import os

base = "/content/drive/MyDrive/HumanBehaviourSimulator"

folders = [
    "datasets",
    "cleaned_data",
    "models",
    "notebooks",
    "reports",
    "plots"
]

for folder in folders:
    os.makedirs(os.path.join(base, folder), exist_ok=True)

print("Folders created successfully!")

Folders created successfully!

In [ ]:
train.to_csv('/content/drive/MyDrive/HumanBehaviourSimulator/cleaned_data/train_clean.csv', index=False)

validation.to_csv('/content/drive/MyDrive/HumanBehaviourSimulator/cleaned_data/validation_clean.csv', index=False)

test.to_csv('/content/drive/MyDrive/HumanBehaviourSimulator/cleaned_data/test_clean.csv', index=False)

In [ ]:
train.to_csv(
    "/content/drive/MyDrive/HumanBehaviourSimulator/datasets/train.csv",
    index=False
)

validation.to_csv(
    "/content/drive/MyDrive/HumanBehaviourSimulator/datasets/validation.csv",
    index=False
)

test.to_csv(
    "/content/drive/MyDrive/HumanBehaviourSimulator/datasets/test.csv",
    index=False
)

print("✅ Original datasets saved successfully!")

✅ Original datasets saved successfully!

In [ ]:
train = pd.read_csv("/content/drive/MyDrive/HumanBehaviourSimulator/cleaned_data/train_clean.csv")
validation = pd.read_csv("/content/drive/MyDrive/HumanBehaviourSimulator/cleaned_data/validation_clean.csv")
test = pd.read_csv("/content/drive/MyDrive/HumanBehaviourSimulator/cleaned_data/test_clean.csv")

In [ ]:
train.head()

,text,labels,id,label,clean_text
0,My favourite food is anything I didn't have to...,[27],eebbqej,27,favourite food anything didnt cook
1,"Now if he does off himself, everyone will thin...",[27],ed00q6i,27,everyone think he laugh screwing people instea...
2,WHY THE FUCK IS BAYLESS ISOING,[2],eezlygj,2,fuck bayless isoing
3,To make her feel threatened,[14],ed7ypvh,14,make feel threatened
4,Dirty Southern Wankers,[3],ed0bdzj,3,dirty southern wanker

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(
    max_features=5000,
    ngram_range=(1,2)
)

In [ ]:
train["clean_text"].isnull().sum()

np.int64(92)

In [ ]:
train["clean_text"] = train["clean_text"].fillna("")
validation["clean_text"] = validation["clean_text"].fillna("")
test["clean_text"] = test["clean_text"].fillna("")

In [ ]:
X_train = tfidf.fit_transform(train["clean_text"])
X_validation = tfidf.transform(validation["clean_text"])
X_test = tfidf.transform(test["clean_text"])  #text to number

In [ ]:
y_train = train["label"]
y_validation = validation["label"]
y_test = test["label"]

In [ ]:
print(X_train.shape)
print(X_validation.shape)
print(X_test.shape)

(43410, 5000)
(5426, 5000)
(5427, 5000)

In [ ]:
print("Missing in text:", train["text"].isnull().sum())

print("Missing in clean_text:", train["clean_text"].isnull().sum())

print("Empty strings:", (train["clean_text"] == "").sum())

train[train["clean_text"].isnull()].head()

Missing in text: 0
Missing in clean_text: 0
Empty strings: 92

Empty DataFrame
Columns: [text, labels, id, label, clean_text]
Index: []

In [ ]:
print(train["clean_text"].isnull().sum())
print(train["clean_text"].dtype)
print(type(train["clean_text"].iloc[0]))

92
object
<class 'str'>

In [ ]:
#lets see wht we did now
feature_names = tfidf.get_feature_names_out()

print(feature_names[:30])

tfidf_df = pd.DataFrame(
    X_train[:10].toarray(),
    columns=tfidf.get_feature_names_out()
)

tfidf_df.head()

['ab' 'abandoned' 'ability' 'able' 'able get' 'abortion' 'absolute'
 'absolutely' 'absolutely love' 'absurd' 'abuse' 'abused' 'abusive'
 'accent' 'accept' 'acceptable' 'accepted' 'accepting' 'access' 'accident'
 'accidentally' 'accomplishment' 'according' 'account' 'accurate'
 'accusation' 'accused' 'ace' 'acid' 'acknowledge']

,ab,abandoned,ability,able,able get,abortion,absolute,absolutely,absolutely love,absurd,...,youtube,youve,youve got,youve never,yr,yr old,yup,zero,zombie,zone
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
import joblib

joblib.dump(
    tfidf,
    "/content/drive/MyDrive/HumanBehaviourSimulator/models/tfidf_vectorizer.pkl"
)

print("✅ TF-IDF Vectorizer Saved!")

✅ TF-IDF Vectorizer Saved!

In [ ]:
!pip install python-docx

Collecting python-docx
  Downloading python_docx-1.2.0-py3-none-any.whl.metadata (2.0 kB)
Requirement already satisfied: lxml>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from python-docx) (6.1.1)
Requirement already satisfied: typing_extensions>=4.9.0 in /usr/local/lib/python3.12/dist-packages (from python-docx) (4.16.0)
Downloading python_docx-1.2.0-py3-none-any.whl (252 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 253.0/253.0 kB 7.5 MB/s eta 0:00:00
Installing collected packages: python-docx
Successfully installed python-docx-1.2.0

In [ ]:
from docx import Document
from docx.shared import Pt

doc = Document()

title = doc.add_heading('Synthetic Human Behaviour Simulator', level=1)
title.runs[0].font.size = Pt(18)

doc.add_heading('Project Documentation', level=2)

doc.add_paragraph("""
Project Goal:
Develop an AI-powered Human Behaviour Simulator capable of predicting emotions,
decision-making patterns, behavioural traits and generating behavioural insights
using Machine Learning, Deep Learning and Large Language Models.

Started: July 2026
Expected Completion: 2026
""")

doc.add_heading("Project Folder Structure", level=2)

doc.add_paragraph("""
HumanBehaviourSimulator/
│
├── datasets/
├── cleaned_data/
├── models/
├── notebooks/
├── reports/
├── plots/
""")

doc.add_heading("Completed Work", level=2)

doc.add_paragraph("""
✔ Notebook 1 - Exploratory Data Analysis (EDA)

• Dataset: GoEmotions
• Training Samples: 43,410
• Validation Samples: 5,426
• Testing Samples: 5,427
• Missing Values Checked
• Text Length Distribution Analysed
• Emotion Distribution Analysed
""")

doc.add_paragraph("""
✔ Notebook 2 - Data Preprocessing

• Lowercasing
• URL Removal
• Punctuation Removal
• Stopword Removal
• Lemmatization
• Emoji Preservation
• Created clean_text column
""")

doc.add_paragraph("""
✔ Notebook 3 - Feature Engineering

Method:
TF-IDF Vectorization

Parameters:
max_features = 5000
ngram_range = (1,2)

Output Shapes:

Training : (43410, 5000)

Validation : (5426, 5000)

Testing : (5427, 5000)
""")

doc.add_heading("Upcoming Work", level=2)

doc.add_paragraph("""
Notebook 4 - Logistic Regression

Notebook 5 - Naive Bayes

Notebook 6 - Random Forest

Notebook 7 - Model Comparison

Notebook 8 - BERT Fine-Tuning

Notebook 9 - Web Application
""")

doc.save("/content/drive/MyDrive/HumanBehaviourSimulator/Project_Documentation.docx")

print("✅ Documentation saved successfully!")

✅ Documentation saved successfully!

In [ ]:
from openpyxl import Workbook

wb = Workbook()
ws = wb.active

ws.title = "Experiments"

headers = [
    "Experiment No",
    "Date",
    "Notebook",
    "Model",
    "Dataset",
    "Features",
    "Accuracy",
    "Precision",
    "Recall",
    "F1 Score",
    "Training Time",
    "Observations",
    "Next Improvement"
]

for col, header in enumerate(headers, start=1):
    ws.cell(row=1, column=col).value = header

wb.save("/content/drive/MyDrive/HumanBehaviourSimulator/Experiment_Log.xlsx")

print("✅ Experiment_Log.xlsx Created Successfully")

✅ Experiment_Log.xlsx Created Successfully

In [ ]:
research_log = """# Research Log

# Synthetic Human Behaviour Simulator

---

## Project Timeline

Start Date: July 2026

Expected Completion: 2026

---

# Entry 1

Date: 19 July 2026

## Objective

Started the Emotion Detection baseline model using the GoEmotions dataset.

## Work Completed

### Notebook 1 - Exploratory Data Analysis (EDA)

- Loaded GoEmotions Dataset
- Analysed dataset structure
- Checked missing values
- Analysed text length distribution
- Analysed emotion distribution
- Understood dataset characteristics

### Notebook 2 - Data Preprocessing

- Converted text to lowercase
- Removed URLs
- Removed punctuation
- Removed stopwords
- Applied Lemmatization
- Preserved emojis
- Created clean_text column
- Saved cleaned datasets

### Notebook 3 - Feature Engineering

- Applied TF-IDF Vectorization
- max_features = 5000
- ngram_range = (1,2)

Output Shapes

Training : (43410, 5000)

Validation : (5426, 5000)

Testing : (5427, 5000)

## Observations

- Only 92 documents became empty after preprocessing.
- Empty documents represent less than 0.3% of the dataset.
- TF-IDF successfully converted text into numerical feature vectors.
- Data leakage avoided by fitting TF-IDF only on the training dataset.

## Problems Faced

- NaN values after loading cleaned dataset.
- Fixed using keep_default_na=False while reading CSV.

## Next Target

Notebook 4

- Logistic Regression
- Accuracy
- Precision
- Recall
- F1 Score
- Confusion Matrix
- Save trained model

---

(Continue adding new entries below every working day.)
"""

with open("/content/drive/MyDrive/HumanBehaviourSimulator/Research_Log.md","w") as f:
    f.write(research_log)

print("✅ Research_Log.md Created Successfully")

✅ Research_Log.md Created Successfully

In [ ]:
ideas_log = """# 💡 Ideas Log

# Synthetic Human Behaviour Simulator

---

## Purpose

This document stores all future ideas, research directions,
feature requests and improvements for the project.

Status Legend

🟢 Planned
🟡 In Progress
🔵 Research Required
✅ Completed

---

# Core AI Features

🟢 Multi-label Emotion Detection

🟢 Personality Prediction

🟢 Behaviour Prediction

🟢 Decision Prediction

🟢 Human Behaviour Simulation

🟢 Behaviour Timeline

🟢 Mood Tracking

🟢 Emotion Trends

🟢 Cognitive Bias Detection

🟢 Behaviour Pattern Recognition

---

# Machine Learning Ideas

🟢 Logistic Regression

🟢 Naive Bayes

🟢 Random Forest

🟢 XGBoost

🟢 SVM

🟢 BERT

🟢 RoBERTa

🟢 DistilBERT

🟢 Ensemble Learning

🟢 Explainable AI (SHAP)

🟢 LIME Interpretability

---

# Web Application Ideas

🟢 User Login

🟢 User Dashboard

🟢 Behaviour History

🟢 Emotion Analytics Dashboard

🟢 Behaviour Reports (PDF)

🟢 Behaviour Graphs

🟢 AI Chat Interface

🟢 Dark Mode

🟢 Admin Dashboard

🟢 Real-time Prediction API

---

# Data Analytics

🟢 Monthly Emotion Trends

🟢 Weekly Behaviour Analysis

🟢 Emotion Distribution

🟢 Word Clouds

🟢 Interactive Charts

🟢 Power BI Dashboard

---

# Research Ideas

🔵 Behaviour Simulation using LLMs

🔵 Human Decision Modelling

🔵 Explainable Behaviour Prediction

🔵 AI Agent Simulation

🔵 Synthetic User Generation

🔵 Multi-Agent Behaviour Simulation

🔵 Reinforcement Learning for Human Decisions

---

# Deployment Ideas

🟢 Docker

🟢 FastAPI

🟢 React Frontend

🟢 PostgreSQL

🟢 AWS Deployment

🟢 CI/CD Pipeline

---

# Future Improvements

- Add multilingual emotion detection.
- Add voice emotion recognition.
- Add facial emotion recognition.
- Build mobile application.
- Build Chrome Extension.
- Compare multiple transformer models.
- Create research paper from project.
- Publish dataset improvements.
- Deploy public demo website.
- Integrate with LLM for behavioural reasoning.

---

# Startup Ideas

- Mental Wellness Assistant
- HR Behaviour Analytics
- Interview Behaviour Prediction
- Student Behaviour Analysis
- Customer Behaviour Analytics
- Behaviour-based Recommendation System

---

(Add new ideas below anytime during the project.)
"""

with open("/content/drive/MyDrive/HumanBehaviourSimulator/Ideas_Log.md", "w") as f:
    f.write(ideas_log)

print("✅ Ideas_Log.md Created Successfully")

✅ Ideas_Log.md Created Successfully