<a href="https://colab.research.google.com/github/RishikaBhawsingka/NLP-ML-project/blob/main/preprocessing4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import re
import string
import nltk

from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

In [ ]:
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...

True

In [ ]:
from datasets import load_dataset

dataset = load_dataset("google-research-datasets/go_emotions")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

README.md:   0%|          | 0.00/9.40k [00:00<?, ?B/s]

simplified/train-00000-of-00001.parquet: reconstructing file:   0%|          |  0.00B / 2.77MB

simplified/train-00000-of-00001.parquet: downloading bytes:           |  0.00B

simplified/validation-00000-of-00001.par(…): reconstructing file:   0%|          |  0.00B /  350kB

simplified/validation-00000-of-00001.par(…): downloading bytes:           |  0.00B

simplified/test-00000-of-00001.parquet: reconstructing file:   0%|          |  0.00B /  347kB

simplified/test-00000-of-00001.parquet: downloading bytes:           |  0.00B

Generating train split:   0%|          | 0/43410 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/5426 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/5427 [00:00<?, ? examples/s]

In [ ]:
import pandas as pd
from datasets import load_dataset

dataset = load_dataset("google-research-datasets/go_emotions")

train_df = pd.DataFrame(dataset["train"])
validation_df = pd.DataFrame(dataset["validation"])
test_df = pd.DataFrame(dataset["test"])

train_df.to_csv("train.csv", index=False)
validation_df.to_csv("validation.csv", index=False)
test_df.to_csv("test.csv", index=False)

In [ ]:
train = pd.read_csv("/content/train.csv")
validation = pd.read_csv("/content/validation.csv")
test = pd.read_csv("/content/test.csv")

In [ ]:
import ast

train["label"] = train["labels"].apply(lambda x: ast.literal_eval(x)[0])
validation["label"] = validation["labels"].apply(lambda x: ast.literal_eval(x)[0])
test["label"] = test["labels"].apply(lambda x: ast.literal_eval(x)[0])

In [ ]:
lemmatizer = WordNetLemmatizer()
stop_words = set(stopwords.words('english'))

def clean_text(text):

    # lowercase
    text = text.lower()

    # remove urls
    text = re.sub(r'http\S+|www\S+', '', text)

    # remove html
    text = re.sub(r'<.*?>', '', text)

    # remove punctuation
    text = text.translate(str.maketrans('', '', string.punctuation))

    # remove numbers
    text = re.sub(r'\d+', '', text)

    # remove extra spaces
    text = re.sub(r'\s+', ' ', text).strip()

    # tokenization
    words = text.split()

    # stopword removal + lemmatization
    words = [
        lemmatizer.lemmatize(word)
        for word in words
        if word not in stop_words
    ]

    return " ".join(words)

In [ ]:
train["clean_text"] = train["text"].apply(clean_text)
validation["clean_text"] = validation["text"].apply(clean_text)
test["clean_text"] = test["text"].apply(clean_text)

In [ ]:
train[["text","clean_text"]].head(10)

,text,clean_text
0,My favourite food is anything I didn't have to...,favourite food anything didnt cook
1,"Now if he does off himself, everyone will thin...",everyone think he laugh screwing people instea...
2,WHY THE FUCK IS BAYLESS ISOING,fuck bayless isoing
3,To make her feel threatened,make feel threatened
4,Dirty Southern Wankers,dirty southern wanker
5,OmG pEyToN iSn'T gOoD eNoUgH tO hElP uS iN tHe...,omg peyton isnt good enough help u playoff dum...
6,Yes I heard abt the f bombs! That has to be wh...,yes heard abt f bomb thanks reply hubby anxiou...
7,We need more boards and to create a bit more s...,need board create bit space name we’ll good
8,Damn youtube and outrage drama is super lucrat...,damn youtube outrage drama super lucrative reddit
9,It might be linked to the trust factor of your...,might linked trust factor friend

In [ ]:
train.isnull().sum()

text          0
labels        0
id            0
label         0
clean_text    0
dtype: int64

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
train.to_csv("train_clean.csv", index=False)
validation.to_csv("validation_clean.csv", index=False)
test.to_csv("test_clean.csv", index=False)

In [ ]:
train.to_csv('/content/drive/MyDrive/HumanBehaviourSimulator/cleaned_data/train_clean.csv', index=False)

validation.to_csv('/content/drive/MyDrive/HumanBehaviourSimulator/cleaned_data/validation_clean.csv', index=False)

test.to_csv('/content/drive/MyDrive/HumanBehaviourSimulator/cleaned_data/test_clean.csv', index=False)

In [ ]:
import os

print(os.listdir("/content"))

['.config', 'train_clean.csv', 'train.csv', 'test_clean.csv', 'validation.csv', 'validation_clean.csv', 'test.csv', 'drive', 'sample_data']